options:
 logging: CLOUD_LOGGING_ONLY
steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/sistema-pokemon/pokemonsystem/poke-front:$COMMIT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args:
      [
        "push",
        "us-central1-docker.pkg.dev/sistema-pokemon/pokemonsystem/poke-front",
      ]